### Ping
GET http://localhost:3003/users
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
     "authorization" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyM2VhOTk3LTM4NTQtNDFhMi05YzBmLTNlZjdhNDY0YTZkNCIsImlhdCI6MTY3NDU3MDQ4Mn0.UzLX_I-Qtd59cF-0nanlOq67L4ycn72WyriVjtlQOeQ"
}

### Pegar todos os Posts
GET http://localhost:3003/posts
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
     "authorization" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImEyM2VhOTk3LTM4NTQtNDFhMi05YzBmLTNlZjdhNDY0YTZkNCIsImlhdCI6MTY3NDU3MDQ4Mn0.UzLX_I-Qtd59cF-0nanlOq67L4ycn72WyriVjtlQOeQ"
}

### Post Feed
POST http://localhost:3003/posts
Content-Type: application/json

{
    "idUser": "a23ea997-3854-41a2-9c0f-3ef7a464a6d4",
    "texto": "Um é tudo, tudo é um O tudo é o mundo, o um sou eu! Tudo é criado a partir de um E tudo retorna a um Tudo existe graças ao um E tudo está contido no um! Mas só com esses ''uns'' juntos, o ''tudo'' pode existir",
    "img": "http://pm1.narvii.com/6305/de85076ea47ebc9c9e8fccf47bc5dc1544a75fd8_00.jpg"
}

### Signup
POST http://localhost:3003/users/register
Content-Type: application/json

{
    "name": "Zane",
    "email": "teste270@gmail.com",
    "password": "123456"
}

### Login
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "password": "123456"
}